# Generated by Django 5.2.4 on 2025-08-05 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wordbank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='単語番号')),
                ('term', models.CharField(max_length=30, verbose_name='単語')),
                ('meaning', models.CharField(max_length=100, verbose_name='意味')),
                ('latest_edited_at', models.DateTimeField(auto_now=True, verbose_name='最終更新日時')),
                ('latest_edited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_edited_words', to=settings.AUTH_USER_MODEL, verbose_name='最終編集者')),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='words', to='wordbank.wordlist', verbose_name='単語帳')),
            ],
            options={
                'verbose_name': '単語一覧',
                'ordering': ['wordlist', 'number'],
            },
        ),
    ]
