# Generated by Django 5.2.4 on 2025-08-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['wordlist', 'number']},
        ),
    ]
