# Generated by Django 5.2.4 on 2025-09-01 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APICostLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.FloatField(verbose_name='推定費用')),
                ('request_id', models.CharField(max_length=64, verbose_name='リクエストID')),
                ('api_model', models.CharField(default='openai', max_length=32, verbose_name='使用API名')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='リクエスト日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='利用者')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
