# Generated by Django 5.2.4 on 2025-09-05 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_apicostlog_delete_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicostlog',
            options={'ordering': ['created_at', 'user']},
        ),
        migrations.AlterField(
            model_name='apicostlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_log', to=settings.AUTH_USER_MODEL, verbose_name='利用者'),
        ),
    ]
